### ISSUE TITLE
get jquery to work

### ISSUE THREAD

**Issue by Nalipp** [LearnTeachCodeSeoul/ltc_attendance#21]
I tried for a while today to get jquery to function on our app without success
looks like we just dropped in this script for our previous project but I was still getting a bootstrap error that we needed to load jquery???

<script src="http://code.jquery.com/jquery-3.1.1.min.js" integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8=" crossorigin="anonymous"></script>

any ideas what i might be missing?

**Comment by mepda** [comment]
what files in the app are you trying to get jQuery to work in?

**Comment by Nalipp** [comment]
all of them should be able to load using the script specified in the layout
but specifically I was trying to use it with the signup form
